name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11':

      - name: Build with Maven
        run: mvn clean package -DskipTests

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Run tests with Maven
        run: mvn test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/demo:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/demo:${{ github.sha }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/demo:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/demo:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/demo:latest